[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r backend/requirements.txt"]

[start]
cmd = "cd backend && alembic upgrade head && python run.py"
